# Server configuration
server:
  context-path: /micro
  port: 8080

# Spring properties
spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql:///prd-4.securegateway.appdomain.cloud:19510inventorydb
    username: dbuser
    password: Pass4dbUs3R
  jpa:
database: MYSQL